name: Swift Coverage Conversion
description: Converts Swift / Xcode code coverage files for processing with e.g. codecov.
author: ser.soft GmbH
inputs:
  search-paths:
    description: A list of search paths (one per line) that should be used for searching coverage data.
    required: true
    default: |
      ./.build
      $HOME/Library/Developer/Xcode/DerivedData
  output:
    description: The path to the output folder to put the converted coverage files in.
    required: true
    default: './.swiftcov'
  format:
    description: The format to write the coverage files in. Can be 'txt' or 'lcov'.
    required: true
    default: 'txt'
  target-name-filter:
    description: A regular expression that is used to filter coverage files by their target names.
    required: false
  ignore-conversion-failures:
    description: If `true`, conversion failures are ignored. If `fail-on-empty-output` is also set to `true`, the action might still fail if all conversions fail.
    required: true
    default: 'false'
  fail-on-empty-output:
    description: If `true`, the action fails if no coverage files were found (output is still set to an empty array).
    required: true
    default: 'false'
outputs:
  files:
    description: The JSON-encoded array of (absolute) file paths that were converted.
runs:
  using: node16
  main: dist/index.js
branding:
  color: gray-dark
  icon: refresh-cw
