#if !canImport(ObjectiveC)
import XCTest

extension MainObjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MainObjectTests = [
        ("testSomeClass", testSomeClass),
        ("testSomeEnum", testSomeEnum),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MainObjectTests.__allTests__MainObjectTests),
    ]
}
#endif
