#if !canImport(ObjectiveC)
import XCTest

extension SomeObjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SomeObjectTests = [
        ("testSomeObject", testSomeObject),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SomeObjectTests.__allTests__SomeObjectTests),
    ]
}
#endif
