name: Pull Request Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test-defaults:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: ^12.4
      - name: Install dependencies
        run: sudo npm i -g typescript @vercel/ncc
      - uses: actions/checkout@v2
      - name: Generate action code
        run: npm run deploy
      - uses: sersoft-gmbh/xcodebuild-action@v1.5.0
        with:
          spm-package: __test__/TestProject
          scheme: TestProject-Package
          action: test
          enable-code-coverage: true
          parallel-testing-enabled: true
      - uses: './'
      - name: Check for produced coverage files
        run: | # check that the directory exists and contains files
          test -d .xcodecov && \
          test "$(find '.xcodecov' -name '*.txt')" != ''
